# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - FDA_Lab_Week_1_Q_1_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CJQyWslw6AlE0O1Cb3khQBIwok0pO6_l

# Q 2.2

Consider the flight timetable

Create the following tables using CREATE TABLE commands.
Populate tables with the data using INSERT commands.

# Table: FLIGHT
| FLIGH_No | DEPART | ORIGIN_AIRPORT | DESINTATION_AIRPORT | ARRIVAL | PLANE_TYPE |
|----------|--------|----------------|---------------------|---------|------------|
| BA687    | 07:30  | Heathrow       | Arlanda             | 09:20   | TriPlus    |
| AF471    | 08:20  | Orly           | JFK                 | 11:20   | XBus       |
| SA572    | 10:15  | Heathrow       | Arlanda             | 12:05   | 707S       |
| BA242    | 11:20  | Heathrow       | Orly                | 12:00   | TriPlus    |
| PA109    | 12:10  | Gatwick        | OHare               | 15:20   | XBus       |


# Table: PLANE

|   | Plane_Type | Max_Seats |
|---|------------|-----------|
| 1 | XBus       | 420       |
| 2 | 707S       | 185       |
| 3 | Triplus    | 275       |

# Table: AIRPORT1 (Origin)

|   | Airport  | Country |
|---|----------|---------|
| 1 | Gatwick  | UK      |
| 2 | Orly     | France  |
| 3 | Heathrow | UK      |


# Table: AIRPORT2 (Destination)

|   | Airport | Country |
|---|---------|---------|
| 1 | O'Hare  | USA     |
| 2 | Orly    | France  |
| 3 | JFK     | USA     |
| 4 | Arlanda | Sweden  |

# Write the following SQL queries.

## A. FlIGHT table
1. Select (or find) information about all flights departing from Heathrow airport.
2. Select information about all flights that depart before 10:15.

(Hint: DEPART data type is TIME. In SQL WHERE clause TIME value should be enclosed in ‘’ such as ’10:15’)


## B. PLANE table
1. Find the capacity of seats of the plane 707S

## C. AIRPORT1 table
1. Find all the origin airports in UK

## D. AIRPORT2 table
1. Find name of the country which has the Arlanda airport
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext sql

!pip install ipython-sql

# Commented out IPython magic to ensure Python compatibility.
# Procedure to run SQL in google colab
#Install ipython-sql
!pip install ipython-sql
#Load SQL extension
# %load_ext sql
#Create SQL Database
# %sql sqlite:///abc.db

#Eg:
#Execute SQL Commands followed by %%sql magic command

# Commented out IPython magic to ensure Python compatibility.
# %sql sqlite:///flights.db

# Commented out IPython magic to ensure Python compatibility.
# 
# 
# %%sql
# CREATE TABLE flights (FLIGHT_No VARCHAR(7),	DEPART,	ORIGIN_AIRPORT VARCGAR(10),	DESINTATION_AIRPORT VARCGAR(10),	ARRIVAL,	PLANE_TYPE VARCHAR(10));
# INSERT INTO flights (FLIGHT_No,	DEPART,	ORIGIN_AIRPORT,	DESINTATION_AIRPORT,	ARRIVAL,	PLANE_TYPE )
# VALUES
# ('BA687', '07:30',	'Heathrow',	'Arlanda','09:20','TriPlus'),
# ('AF471', '08:20',	'Orly',	'JFK','11:20','XBus'),
# ('SA572', '10:15',	'Heathrow',	'Arlanda','12:05','707S'),
# ('BA242', '11:20',	'Heathrow',	'Orly','12:00','TriPlus'),
# ('PA109', '12:10',	'Gatwick',	'OHare','15:20','XBus');
#

"""**ANS TO THE QUESTION A (1)**"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT*FROM flights WHERE ORIGIN_AIRPORT = 'Heathrow';

"""**ANS TO THE QUESTION A(2)**"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT*FROM flights WHERE DEPART < '10:15';

"""**ANS TO THE QUESTION B**"""

# Commented out IPython magic to ensure Python compatibility.
# 
# %%sql
# CREATE TABLE plane (Plane_Type VARCHAR(10), Max_Seats INT);
# INSERT INTO plane (Plane_Type, Max_Seats)
# VALUES
# ('XBus',420),
# ('707S',185),
# ('Triplus',275);
# SELECT Max_Seats FROM plane WHERE Plane_Type = '707S';

"""**ANS TO THE QUESTION C**"""

# Commented out IPython magic to ensure Python compatibility.
# 
# %%sql
# CREATE TABLE airport1 (Airport VARCHAR(10), Country VARCHAR(10));
# INSERT INTO airport1 (Airport, Country)
# VALUES
# ('Gatwick','UK'),
# ('Orly','France'),
# ('Heathrow','UK');
# 
# SELECT * FROM airport1 WHERE Country = 'UK';
#

"""**ANS TO THE QUESTION D**"""

# Commented out IPython magic to ensure Python compatibility.
# 
# 
# %%sql
# CREATE TABLE airport2 (Airport VARCHAR(10), Country VARCHAR(10));
# INSERT INTO airport2 (Airport, Country)
# VALUES
# ('O''Hare','USA'),
# ('Orly','France'),
# ('JFK','USA'),
# ('Arlanda','Sweden');
# 
# SELECT Country FROM airport2 WHERE Airport = 'Arlanda';
#