# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - FDA_Lab_Week_1_Q_1_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GuCFDV4vRJg9TfIhmdkLOmkimTx20ZwN

# Q 2.3
Create tables called Films and Showing using SQL CREATE TABLE commands.

Populate the tables with values using INSERT INTO ... VALUES ... commands.

Example: data of the tables include:


# Table: Films
| Title              | Director  | Actor     |
|--------------------|-----------|-----------|
| Shirley Valentine  | Gilbert   | Collins   |
| Shirley Valentine  | Gilbert   | Lipman    |
| The Pianist        | Polanski  | Lipman    |
| A Single Man       | Ford      | Firth     |
| Mama Mia           | Lloyd     | Firth     |
| Mama Mia           | Lloyd     | Walters   |
| Chinatown          | Polanski  | Nicholson |
| Chinatown          | Polanski  | Polanski  |

# Table: Showing
| Title             | Cinema  |
|-------------------|---------|
| Chinatown         | Odeon   |
| Shirley Valentine | Odeon   |
| The Pianist       | Phoenix |
| A Single Man      | Vue     |
| A Single Man      | Odeon   |
| Mama Mia          | Vue     |
| Chinatown         | Vue     |

1. Check the data of your tables using SELECT * FROM <table name>
2. Write a SELECT query that retrieves name(s) of film(s) which are directed by Polanski.
3. Write a SELECT query that retrieves name(s) of film(s) and actors which are directed by Lloyd.
4. Delete a record from the table ‘Showing’ where Cinema is Phoenix.
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext sql

# Commented out IPython magic to ensure Python compatibility.
# %sql sqlite:///films.db

"""**ANS TO THE QUESTION NO 1**"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# CREATE TABLE Films (
#   Title VARCHAR(255),
#   Director VARCHAR(255),
#   Actor VARCHAR(255)
# );
# 
# INSERT INTO Films (Title, Director, Actor) VALUES
#   ('Shirley Valentine', 'Gilbert', 'Collins'),
#   ('Shirley Valentine', 'Gilbert', 'Lipman'),
#   ('The Pianist', 'Polanski', 'Lipman'),
#   ('A Single Man', 'Ford', 'Firth'),
#   ('Mama Mia', 'Lloyd', 'Firth'),
#   ('Mama Mia', 'Lloyd', 'Walters'),
#   ('Chinatown', 'Polanski', 'Nicholson'),
#   ('Chinatown', 'Polanski', 'Polanski');
# 
# CREATE TABLE Showing (
#   Title VARCHAR(255),
#   Cinema VARCHAR(255)
# );
# 
# INSERT INTO Showing (Title, Cinema) VALUES
#   ('Chinatown', 'Odeon'),
#   ('Shirley Valentine', 'Odeon'),
#   ('The Pianist', 'Phoenix'),
#   ('A Single Man', 'Vue'),
#   ('A Single Man', 'Odeon'),
#   ('Mama Mia', 'Vue'),
#   ('Chinatown', 'Vue');
# 
# SELECT * FROM Showing;
#

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM Films;

"""**ANS TO THE QUESTION NO 2**"""

# Commented out IPython magic to ensure Python compatibility.
# 
# %%sql
# SELECT Title FROM Films WHERE Director = 'Polanski'
#

"""**ANS TO THE QUESTION NO 3**"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT Films.Title, Films.Actor FROM Films WHERE Films.Director = 'Lloyd'

"""**ANS TO THE QUESTION NO 4**"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# DELETE FROM Showing WHERE Cinema = 'Phoenix'
#

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM Showing;