# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - Q_3_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qpv9v2fnpVOSlggqzTlqxWbC5CLjyGHa

**3.1: Pandas**

Load the titanic.csv as a dataframe. Create dataframes df_pclass1, df_pclass2 and df_pclass3 corresponding to pclass = 1, 2 and 3 respectively.
For pclass = 1, find the number of passengers with ages 20, 21 and 22, respectively. Sort the dataframe titanic_df by ageIn the dataframe titanic_df, increase the fare of all passengers whose age is 20 or higher, by 5.
"""

import pandas as pd
titanic=pd.read_csv('titanic.csv')
titanic=pd.DataFrame(titanic)

df_pclass1=titanic[titanic['Pclass']==1]
df_pclass2=titanic[titanic['Pclass']==2]
df_pclass3=titanic[titanic['Pclass']==3]

p20=df_pclass1[df_pclass1['Age']==20]
p21=df_pclass1[df_pclass1['Age']==21]
p22=df_pclass1[df_pclass1['Age']==22]
print('The number of passengers with age 20 is',len(p20))
print('The number of passengers with age 21 is',len(p21))
print('The number of passengers with age 22 is',len(p22))

sorted_titanic=titanic.sort_values(by='Age')
sorted_titanic.loc[sorted_titanic['Age']>=20,'Fare']+=5

print(sorted_titanic[sorted_titanic['Age']>20])

"""First we have to upload Titanic.csv and then create dataframes for each passenger class.Get the number of passengers with ages 20, 21 and 22.perform sorting dataframe by age and increase fare of all passengers aged 20 or higher by 5 and then last but not the least remove NAN values."""