# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - Question 6.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DmtYQO4bjp8_BUnrBhc82TIQ4daUuDuH

#6.1 Visualization using Matplotlib - mtcars

The dataset used for this analysis is "mtcars.csv."

1. Create a scatterplot to visually examine the correlation between horsepower and miles per gallon.
2. Create a bar chart to visually represent the count of cars for each gear type.
3. Create a histogram to visually represent the distribution of car weights.
4. Create boxplots to visually represent the variation in mpg for different cylinder counts.

Link for Dataset
https://drive.google.com/file/d/1fvY5zWBwoWqoJ2SVveYo881f12Ps9Pd4/view?usp=drive_link
"""

from google.colab import drive
drive.mount('/content/drive')

"""Ans to the question no: 1

after import necessary library we use scatterplot because here we are showing  relative points between horsepower and miles per gallon.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/drive/MyDrive/m123/mtcars.csv')

plt.figure(figsize=(8,6))
plt.scatter(df['hp'], df['mpg'], color='blue')
plt.title('Horsepower vs. Miles per Gallon (mpg)')
plt.xlabel('Horsepower (hp)')
plt.ylabel('Miles per Gallon (mpg)')
plt.grid(True)
plt.show()

"""Ans to the question no: 2

As here we have to counts cars under a catagorical data gear type. where counting of card showing by the bars. That's why we used bar chart here.
"""

plt.figure(figsize=(8,6))
df['gear'].value_counts().plot(kind='bar', color='green')
plt.title('Count of Cars for Each Gear Type')
plt.xlabel('Gear Type')
plt.ylabel('Count of Cars')
plt.xticks(rotation=0)
plt.show()

"""Ans to the question no: 3
here values are continuous for that reason we used histogram.
"""

plt.figure(figsize=(8,6))
plt.hist(df['wt'], bins=10, color='purple', edgecolor='black')
plt.title('Distribution of Car Weights')
plt.xlabel('Weight (1000 lbs)')
plt.ylabel('Frequency')
plt.show()

"""Ans to the question no: 4

by thus box plot we can get the rages of maximam, mean & minimum if data.
"""

plt.figure(figsize=(8,6))
sns.boxplot(x='cyl', y='mpg', data=df, palette='Set2')
plt.title('Miles per Gallon (mpg) by Cylinder Count')
plt.xlabel('Number of Cylinders')
plt.ylabel('Miles per Gallon (mpg)')
plt.show()