# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - Q_3_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ze9mKc5SSRUFGPTCgFUneONV967yVcV6

**3.6: Numpy**

Confusion matrix is given

The following was obtained after a classification.

| Fruit    | Apple | Banana | Orange |
|----------|-------|--------|--------|
| **Apple**  |  18   |   3    |   9    |
| **Banana** |   1   |  30    |   4    |
| **Orange** |   7   |   5    |  23    |



Compute the accuracy of classification.
"""

import numpy as np
confusion_matrix = np.array([[18, 3, 9],
                             [1, 30, 4],
                             [7, 5, 23]])

# sum of dig
correct_predictions = np.trace(confusion_matrix)

# tot of predic
total_predictions = np.sum(confusion_matrix)
accuracy = correct_predictions / total_predictions

print("Accuracy of classification:", accuracy)