# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - Q_3_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T3tnQfUM4fbUBaCAWI6NKLGgO7WDFqbl

**3.3: Numpy**


Create a random 1 x 40 one dimensional array and convert it to a 8 x 5 two dimensional numpy array.
"""

import numpy as np

one_d_array = np.random.rand(40)
two_d_array = one_d_array.reshape(8, 5)

print(two_d_array)