# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - Question_4_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m3QeNgAPeQSpUL4juPdOoVj8GDkQWgPN

#  4.1 Data Cleaning using Pandas

Consider the data from Lending Club (Dataset/lending_club_loans.csv), a marketplace for
personal loans that matches borrowers who are seeking a loan with investors looking to lend
money and make a return.

1. The first line in the dataset contains some extraneous text instead of the column titles.
This text prevents the data set from being parsed properly by the pandas library. Hence
remove the first line. (Hint: This can be easily done while reading the csv file itself )
2. Remove the ‘desc’ column: it contains a long text explanation for the loan that we won’t
need.
3. Remove the ‘url’ column: it contains a link to each on Lending Club which can only be
accessed with an investor account.
4. Removing all columns with more than 50% missing values: This will allow us to work
faster, and our data set is large enough that it will still be meaningful without them.
5. Display the number of samples and features that are present after the above operations.

Ans no 1
"""

import pandas as pd
df = pd.read_csv('lending_club_loans.csv', skiprows=1)

"""Ans no 2 & 3"""

df.drop(['desc', 'url'], axis=1, inplace=True)

"""Ans no 4"""

threshold = len(df) * 0.5
df.dropna(thresh=threshold, axis=1, inplace=True)

"""Ans no 5"""

print(f"Number of samples: {df.shape[0]}")
print(f"Number of features: {df.shape[1]}")