# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - Question_2_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16p1mHCXMQdQRc0w7-GxpiU_EZ3fJ926h

# 2.3 Import XML in python  

Write Python code to import (read) data from the XML document (as in Project 3.1)

    a) Display (print) all the data records in XML format.

    b) Calculate the percentage of the number of each social network users with respect to the world population.
    
For instance, world population is 7800000000 (7.8 billions, approx.). Based on the above data, Facebook would have 34.63% users of the world population.
"""

import xml.etree.ElementTree as ET
Tree = ET.parse ('networks.xml')
root = Tree.getroot()

"""**Ans to the question A**"""

for network in root:
  for data in network:
    print(data.tag,":",data.text)
  print("\n")

"""**Ans to the Question B**"""

world_population = 7800000000
for Network in root:
  name = Network.find('Name').text
  users = int(Network.find('Users').text)
  percentage = (users / world_population) * 100
  print(f"{name} has {percentage:.2f}% users of the world population.")