# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - Q_3_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QaX7MTeFcgzBpXOkJfOyIjUvWDvpS7w5

# 3.2 Numpy
Create an array from 0 to 9 and multiply by 2
"""

import numpy as np
array = np.arange(10)
multiplied_array = array * 2
print(multiplied_array)