# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - Q_3_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14KQGMLNJltOVdzoUZPnvFaJEf142-U7n

**3.4: Numpy**

Create a 1 x 2000 numpy array with stepwise sequence from 1 to 2000 and then convert into a 40 x 50 two dimensional numpy array.
Further, index the array correctly to return the value 435.
Index the array correctly to return the value 951.
"""

import numpy as np
one_d_array = np.arange(1, 2001)

two_d_array = one_d_array.reshape(40, 50)

value_435 = two_d_array[8, 34]
value_951 = two_d_array[19, 0]

print("Value 435:", value_435)
print("Value 951:", value_951)

"""we can create the array, reshape it, and index it to return the specified values: Value 435: It is located at the 9th row and 35th column in the 40x50 array. Since Python uses 0-based indexing, this corresponds to index [8, 34]. Value 951: It is located at the 20th row and 1st column, which corresponds to index [19, 0]."""