# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - Question_2_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YTmHqYBdCHTGzOeTa-ydhnYX8y99xveu

# 2.1 XML Document 1
Statista* provides information on the number of users of different social (media) networks. Consider the following social networks and represent the data in an XML document. Data about other social networks (available on Statista) can also be included.
Note: There is some update (increase) in the data on Statista website. But we use the following data for this practical.

| Rank | Social networks    | Users         |
|:----:|--------------------|---------------|
|   1  | Facebook           | 2,701,000,000 |
|   2  | YouTube            | 2,000,000,000 |
|   3  | Whatsapp           | 2,000,000,000 |
|   4  | Facebook Messenger | 1,300,000,000 |
|   5  | Weixin/WeChat      | 1,206,000,000 |
|   6  | Instragram         | 1,158,000,000 |
|   7  | Tik Tok            | 689,000,000   |

*https://www.statista.com/statistics/272014/global-social-networks-ranked-by-number-of-users/

Use text editor of your choice (e.g., notepad, notepad++, etc.) to create an XML document for representing the above information.

You can validate your XML document by checking its correctness using the W3 XML validator.

http://www.w3schools.com/xml/xml_validator.asp

<?xml version="2.6" encoding="UTF-8"?>

<Social_Networks>
  <Network>
    <Rank>1</Rank>
    <Name>Facebook</Name>
    <Users>2701000000</Users>
  </Network>

  <Network>
    <Rank>2</Rank>
    <Name>YouTube</Name>
    <Users>2000000000</Users>
  </Network>

  <Network>
    <Rank>3</Rank>
    <Name>Whatsapp</Name>
    <Users>2000000000</Users>
  </Network>

  <Network>
    <Rank>4</Rank>
    <Name>Facebook Messenger</Name>
    <Users>1300000000</Users>
  </Network>

  <Network>
    <Rank>5</Rank>
    <Name>Weixin/WeChat</Name>
    <Users>1206000000</Users>
  </Network>

  <Network>
    <Rank>6</Rank>
    <Name>Instragram</Name>
    <Users>1158000000</Users>
  </Network>

  <Network>
    <Rank>7</Rank>
    <Name>Tik Tok</Name>
    <Users>689000000</Users>
  </Network>
</Social_Networks>
"""