# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - Question_2_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TWcWYg-5uWkhbnbHyICQnshrmD92swft

# 2.5 XML + SQL using Python
This exercise is to integrate data from semi-structured (XML) and structured (SQL) data sources using Python.

a) Write Python code in order to read (import) the XML document (as in Exercise 3.4).

b) Print the content of whole XML document – including element names/tags and data.

c) Use SQLite database to create SQL table and store the following data about population of countries

| No | Country | Population |
|:--:|---------|------------|
|  1 | China   | 1433783686 |
|  2 | India   | 1366417754 |
|  3 | Brazil  | 211049527  |
|  4 | Mexico  | 127575529  |
|  5 | Japan   | 126860301  |

Source: UN data

d) Write Python code to import the above data from SQL table (see examples from previous lecture/practical about importing data from SQL table into Python)

e) Write SQL query to select data from the SQL table

f) Calculate the percentage of population of a city (as in Exercise 3.4) with respect to the total population of a country, e.g., calculate percentage of Tokyo’s population (37 million) with respect to Japan’s population which is 126,860,301. Tokyo population would be 29.17% of the Japans’ population.

**Ans to the question A**
"""

import xml.etree.ElementTree as ET
tree = ET.parse('citypop.xml')
root = tree.getroot()

"""**Ans to the question B**"""

ET.dump(tree)

"""**Ans to the question C**"""

import sqlite3
conn = sqlite3.connect('population.db')
cursor = conn.cursor()

cursor.execute('''DROP TABLE IF EXISTS countries''')

cursor.execute('''
    CREATE TABLE IF NOT EXISTS countries (
        No INTEGER PRIMARY KEY,
        Country TEXT,
        Population INTEGER
    )
''')

data = [
    (1, 'China', 1433783686),
    (2, 'India', 1366417754),
    (3, 'Brazil', 211049527),
    (4, 'Mexico', 127575529),
    (5, 'Japan', 126860301)
]
cursor.executemany('INSERT INTO countries VALUES (?, ?, ?)', data)

conn.commit()
conn.close()

"""**Ans to the question D**"""

conn = sqlite3.connect('population.db')
cursor = conn.cursor()

cursor.execute('SELECT * FROM countries')
rows = cursor.fetchall()

for row in rows:
  print(row)

conn.close()

"""**Ans to the question E**"""

conn = sqlite3.connect('population.db')
cursor = conn.cursor()

query = "SELECT * FROM countries WHERE Country = 'Japan'"
cursor.execute(query)
japan_population = cursor.fetchone()
print(f"\nPopulation of Japan: {japan_population[2]}")

conn.close()

"""**Ans to the question F**"""

import xml.etree.ElementTree as ET
import sqlite3

tree = ET.parse('citypop.xml')
root = tree.getroot()

conn = sqlite3.connect('population.db')
cursor = conn.cursor()

print("\nPercentage of City Population with Respect to Country Population:")
for city in root.findall('City'):
    city_name = city.find('CityName').text
    city_population = int(city.find('Population').text)
    country_name = city.find('CountryName').text

    cursor.execute("SELECT Population FROM Countries WHERE Country = ?", (country_name,))
    country_population = cursor.fetchone()[0]

    percentage = (city_population / country_population) * 100
    print(f"{city_name} in {country_name}: {percentage:.2f}%")