# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - Question_7.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jpO4YBOyylG2e75Mh1BNqQlVGLyK_yfI

# **Visualization using Seaborn**


Given a dataset of children’s information, including their age, height, weight, and gender, you are tasked with visualizing the relationships between these variables using Seaborn. You will create a variety of plots to explore how height varies with age and how factors like gender and weight influence this relationship.

**Dataset**:  
The dataset contains the following columns:
- `age`: Age of the child (in years)
- `height`: Height of the child (in inches)
- `weight`: Weight of the child (in pounds)
- `gender`: Gender of the child (`'boy'` or `'girl'`)

**Tasks**:

1. **Scatterplot of Age and Height**:  
   Create a scatterplot using Seaborn to visualize the relationship between age (x-axis) and height (y-axis) for all children. Label the axes and add an appropriate title.

2. **Distinguish Boys from Girls in Scatterplot**:  
   Modify the scatterplot from Task 1 to differentiate between boys and girls. Use different markers or colors for boys and girls to visualize potential gender-specific growth patterns.

3. **Boxplots for Boys and Girls**:  
   Create boxplots using Seaborn to visualize the distribution of heights for boys and girls. This will allow you to compare the height ranges between the two groups.

4. **Scatterplot with Weight Mapped to Point Size**:  
   Create a scatterplot where age is on the x-axis and height is on the y-axis. Map the size of each point to the child's weight, so that heavier children have larger points. Use different colors for boys and girls.

5. **Histogram of Heights with Gender Differentiation**:  
   Create a histogram using Seaborn to show the distribution of heights for all children. Color-code the histogram bars to differentiate between boys and girls.

6. **Probability Density Approximation of Heights**:  
   Create a histogram with an overlay of a probability density estimation (KDE) to provide a smooth representation of the height distribution. Use different colors for boys and girls in the plot.

7. **Faceted Histograms for Boys and Girls**:  
   Create separate histograms for boys and girls to visualize the distribution of heights for each gender. Use faceting in Seaborn to display the histograms side by side for easier comparison.

---
"""

from google.colab import drive
drive.mount("/content/drive", force_remount=True)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv('/content/drive/MyDrive/Badhon/heightweight.csv')

"""Asn to question no 1"""

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='ageYear', y='heightIn')
plt.title('Scatterplot of Age vs Height')
plt.xlabel('Age (years)')
plt.ylabel('Height (inches)')
plt.show()

"""Ans to the question no 2"""

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='ageYear', y='heightIn', hue='sex', style='sex', markers=['o', 's'])
plt.title('Scatterplot of Age vs Height by Gender')
plt.xlabel('Age (years)')
plt.ylabel('Height (inches)')
plt.legend(title='Gender')
plt.show()

"""Ans to the question no 3"""

plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x='sex', y='heightIn')
plt.title('Boxplot of Heights by Gender')
plt.xlabel('Gender')
plt.ylabel('Height (inches)')
plt.show()

"""Ans to the question no 4"""

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='ageYear', y='heightIn', size='weightLb', hue='sex', sizes=(20, 200), alpha=0.7, legend=False)
plt.title('Scatterplot of Age vs Height with Weight as Point Size')
plt.xlabel('Age (years)')
plt.ylabel('Height (inches)')
plt.show()

"""Ans to the questio no 5"""

plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='heightIn', hue='sex', element='step', stat='density',  bins=30)
plt.title('Histogram of Heights by Gender')
plt.xlabel('Height (inches)')
plt.ylabel('Density')
plt.show()

"""Ans to the question no 6"""

plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='heightIn', hue='sex', kde=True, element='step', stat='density', common_norm=False, bins=30)
plt.title('Height Distribution with KDE by Gender')
plt.xlabel('Height (inches)')
plt.ylabel('Density')
plt.show()

"""Ans to the question no 7"""

g = sns.FacetGrid(df, col='sex', height=5, aspect=1)
g.map(sns.histplot, 'heightIn', bins=30, kde=True, color='blue', stat='density')
g.set_titles(col_template='{col_name} Height Distribution')
plt.show()