# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - FDA_Lab_Week_1_Q_1_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JwzknnctM_JPXP-2UGJQSZZVPYV8_kBH

# Q 2.4

This exercise demonstrates how we can connect to a sqlite database from python and query the database in python.
Please read through the documentation of the sqlite3 module.

A sqlite database is given to you: [‘cinema.db’](https://drive.google.com/file/d/17dWRHUDYMslEzuJ_3kBb7p21vnJLcHHO/view?usp=sharing):

Please follow the below steps in Python:
1. Firstly, sqlite3 module has to be imported using
import sqlite3
2. Then we have to create a connection to the database. This can be done by
conn = sqlite3.connect("database_name.db")
3. The above command will connect to the database if already present; if not
creates a database with the given name.
4. A cursor has to be created using this connection established.
 cursor = conn.cursor()
5. A query can be executed using execute() method. This method is to be invoked with the help of the cursor that has been created.
 cursor.execute(“SQL QUERY”)
6. Executing the above command, The returned data from the given query will be saved in the cursor itself.
7. To fetch all the selected data from the query, we can use the fetchall() command
rows= cursor.execute(“SQL QUERY”).fetchall()

**Q1.** Write a SELECT query that retrieves name(s) of film(s) which are directed by Polanski.

**Q2.** Write a SELECT query that retrieves name(s) of film(s) and actors which are directed by Lloyd.

**Q3.** Delete a record from the table ‘Showing’ where Cinema is Phoenix.  


**Note:** You may use **DB browser** to check the contents in the given database.
"""

import sqlite3
conn = sqlite3.connect("cinema.db")
cursor = conn.cursor()

cursor.execute("SELECT * FROM Showing").fetchall()

cursor.execute("SELECT DISTINCT Title FROM Films WHERE Director= 'Polanski' ")
polanski_films=cursor.fetchall()
print("Films directed by Polanski:")
for film in polanski_films:
  print(film[0])

cursor.execute ("DELETE FROM Showing WHERE Cinema ='Phoenix'")
cursor.execute("SELECT * FROM Showing").fetchall()

cursor.execute("SELECT Title,Actor FROM Films WHERE Director='Lloyd'")
lloyd_films_actors=cursor.fetchall()
print("\nFilms and actors directed by Lloyd:")
for film, actor in lloyd_films_actors:
  print(f"Film: {film}, Actor: {actor}")

