# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - Question_2_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-ySod8dLQ9rnBEEWeMLvD0-QSVHGSsA

# 2.6 XML Schema (Not assigned)

Define XML schema for the XML document you have written in project 3.1.

Validate the XML schema using the schema validator available at: http://schneegans.de/sv/
"""

<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Root element -->
  <xs:element name="Social_Networks">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Network" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Rank" type="xs:int"/>
              <xs:element name="Name" type="xs:string"/>
              <xs:element name="Users" type="xs:long"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>