# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - Question_4_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xK85uQutnWXTWLzUBxCDB7An49Slad6_

# 4.2 Merging Data Frames

Download the MovieLens 1M dataset. It contains 1 million ratings collected from 6000 users
on 4000 movies. Ratings, user information and movie information. Each table can be loaded
into pandas.
1. Merge the users table with the ratings table. Now merge the above table with the movies
table.
2. Find the list of movies that has atleast 250 ratings
3. Obtain the mean rating of each movie
4. Obtain the mean rating of films across male and female gender
5. Find out the top 10 films among female viewers.
"""

import pandas as pd

users = pd.read_csv('users.dat', sep='::', engine='python', header=None, names=['UserID', 'Gender', 'Age', 'Occupation', 'Zip-code'])
ratings = pd.read_csv('ratings.dat', sep='::', engine='python', header=None, names=['UserID', 'MovieID', 'Rating', 'Timestamp'])
movies = pd.read_csv('movies.dat', sep='::', engine='python', header=None, names=['MovieID', 'Title', 'Genres'], encoding='latin-1')

print(users.head())
print(ratings.head())
print(movies.head())

"""**Ans no 1:**
Here, I will merge the data across the three files:

Merge the users table with the ratings table based on the user_id columnand Merge the resulting table with the movies table using the movie_id column.
"""

user_ratings = pd.merge(users, ratings, on='UserID')

merged_data = pd.merge(user_ratings, movies, on='MovieID')

print(merged_data.head())

"""**Ans no 2:**
After merging, I will group the data by movie_id and count the number of ratings each movie has.

"""

movie_counts = merged_data['Title'].value_counts()
popular_movies = movie_counts[movie_counts >= 250].index.tolist()

popular_movies_data = merged_data[merged_data['Title'].isin(popular_movies)]

print(f"Number of movies with at least 250 ratings: {len(popular_movies)}")

"""**Ans no 3:**
I will calculate the mean rating for each movie by grouping the merged table by movie_id and calculating the average of the rating column.
"""

mean_ratings = popular_movies_data.groupby('Title')['Rating'].mean().sort_values(ascending=False)
print(mean_ratings.head())

"""**Ans no 4:**
After filtering, I will group the data by movie_id and gender and calculate the mean rating separately for male and female viewers.
"""

mean_ratings_by_gender = popular_movies_data.groupby(['Title', 'Gender'])['Rating'].mean().unstack()
print(mean_ratings_by_gender.head())

"""**Ans no 5:**
Sort the movies based on the average rating given by female viewers and select the top 10 movies.
"""

top_female_ratings = mean_ratings_by_gender['F'].sort_values(ascending=False).head(10)
print("Top 10 films among female viewers:")
print(top_female_ratings)

