# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - Q_3_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOvBBJtm_HWNxUtX7kallU-xwbl4wZ9C

**3.5: Numpy**

Normalize the vector represented by numpy array : ([3, 5, 1, 2, 4]) to find the unit vector in the same direction.
"""

import numpy as np
vector = np.array([3, 5, 1, 2, 4])

magnitude = np.linalg.norm(vector)

unit_vector = vector / magnitude

print("Unit vector:", unit_vector)

"""Magnitude: The magnitude of the vector is calculated using np.linalg.norm(vector). Unit vector: The vector is normalized by dividing each of its components by the magnitude. The output will be the unit vector in the same direction as the original vector [3, 5, 1, 2, 4]."""