# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - Question_2_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1snphEcUaBImm9gYH69NTg5Fj2XmJEkl7

# 2.2 XML Document correct errors

Consider the following XML document. This document is not well-formed.

Correct errors and make it well-formed XML document.
```
 <?xml version="1.0" encoding="UTF-8" ?>
  <students>
    <student id="100026">
      <name>Joe Average<age>21</name></age>
      <course>MSc Data Analytics</Course>
	  <grade>B</grade>
	  <average_mark>62<average_mark/>
	</student>
    <student id 100027>
      <Name>Jack Doe</name>
      <age>35<age/>
      <course>Business Management</course>
	  <GRADE>A</grade>
	  <average_mark>75</average_mark>
    </student>
	<student id="100028">
      <name>Ahmed Ali</name>
      <age>28</age>
      <course>MSc Computing Science</course>
	  <grade>B<average_mark>65</grade></average_mark>
    </student>
  </students>
  ```

```
<?xml version="1.0" encoding="UTF-8" ?>
<students>
  <student id="100026">
    <name>Joe Average</name>
    <age>21</age>
    <course>MSc Data Analytics</course>
    <grade>B</grade>
    <average_mark>62</average_mark>
  </student>
  <student id="100027">
    <name>Jack Doe</name>
    <age>35</age>
    <course>Business Management</course>
    <grade>A</grade>
    <average_mark>75</average_mark>
  </student>
  <student id="100028">
    <name>Ahmed Ali</name>
    <age>28</age>
    <course>MSc Computing Science</course>
    <grade>B</grade>
    <average_mark>65</average_mark>
  </student>
</students>
```
"""