# -*- coding: utf-8 -*-
"""BADHON DATTA.PROTTOY - FDA_Lab_Week_1_Q_1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12pCWoR21mDBiX4K6k6mPEzrvpdom8HWa

# Q 1.1
## Instructions
---
Table: FLIGHT-TIMETABLE

| FLIGHT # | DEPART |  ORIGIN  |         | DESTINATION |         | ARRIVAL | PLANE TYPE | MAX SEATS |
|:--------:|:------:|:--------:|:-------:|:-----------:|:-------:|:-------:|:----------:|:---------:|
|          |        |  AIRPORT | COUNTRY |   AIRPORT   | COUNTRY |         |            |           |
|   BA687  |  07:30 | Heathrow |    UK   |   Arlanda   |  Sweden |  09:20  |   TriPlus  |    275    |
|   AF471  |  08:20 |   Orly   |  France |     JFK     |   USA   |  11:20  |    XBus    |    420    |
|   SA572  |  10:15 | Heathrow |    Uk   |   Arlanda   |  Sweden |  12:05  |    707S    |    185    |
|   BA242  |  11:20 | Heathrow |    UK   |     Orly    | France  |  12:00  |   TriPlus  |    275    |
|   PA109  |  12:10 |  Gatwick |    UK   |    O'Hare   |   USA   |  15:20  |    XBus    |    420    |




Using the above table answer the following questions.
1. In which Normal Form is the above relation? Why?
2. Identify functional dependencies.
3. Decompose (or normalize) the above relation to 3NF
---
**Note: Answers to the theory questions must be written as markdown, by adding text cells below this question.**

---

You can find basic markdown syntax (creating table, adding figures, etc) at: https://www.markdownguide.org/cheat-sheet/

Note: You may also use other free online tools available online
(eg: https://www.tablesgenerator.com/markdown_tables) to create markdown tables.

# Evaluation Criteria:

| Criteria                    | Excellent (80-100)                          | Good (50-70)                                      | Needs Improvement (0-40)            |
|-----------------------------|---------------------------------------------|--------------------------------------------------|-------------------------------------|
| Completion of Experiment (20) | Completed and showed output to TA           | Partially completed and showed some output       | Did not complete or show output     |
| Viva (15 + 10)              | Answered confidently and accurately         | Answered correctly, but with hesitation          | Struggled to answer or incorrect    |
| Lab Report (10)             | Well-written, clear, and concise            | Good, but with errors or lacking clarity         | Poor quality or not submitted       |
| Attendance (5)              | Attended the lab session                    | Late or left early                               | Did not attend                      |

**Ans to the question No 1**

The relation is in 1N form.

**Ans to the question no 2**

In this table functional dependencies are

Flights - Depart , arrival, Origin , Destination, plane type , Max seat

Origin airport - Origin country

Destination Airport - Destination Country

**Ans to the question no 3**
###Table: FLIGHT

| FLIGHT # | DEPART | ARRIVAL |
|----------|--------|---------|
| BA687    | 07:30  | 09:20   |
| AF471    | 08:20  | 10:15   |
| SA572    | 10:15  | 12:05   |
| BA424    | 11:20  | 12:00   |
| PA109    | 12:10  | 15:20   |

###Table: FLIGHT_TYPE

| FLIGHT # | PLANE TYPE | MAX SEAT |
|----------|------------|----------|
| BA687    | TRIPLUS    | 275      |
| AF471    | XBUS       | 420      |
| SA572    | 707S       | 185      |
| BA424    | TRIPLUS    | 275      |
| PA109    | XBUS       | 420      |

###Table: FLIGHT_ORIGIN

| FLIGHT # | ORIGIN (COUNTRY) | ORIGIN(AIRPORT) |
|----------|------------------|-----------------|
| BA687    | UK               | HEATHROW        |
| AF471    | FRANCE           | ORLY            |
| SA572    | UK               | HEATHROW        |
| BA424    | UK               | HEATHROW        |
| PA109    | UK               | GATWICK         |

###Table: FLIGHT_DESTINATION

| FLIGHT # | DESTINATION(AIRPORT) | DESTINATION(COUNTRY) |
|----------|----------------------|----------------------|
| BA687    | ARLANDA              | SWEDEN               |
| AF471    | JFK                  | USA                  |
| SA572    | ARLANDA              | SWEDEN               |
| BA424    | ORLY                 | FRANCE               |
| PA109    | O'HARE               | USA                  |
"""